name: Run hello.sh on push
 
on:
  push:
    branches:
      - "feature-*"
  pull_request:
    branches:
      -main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Run hello.sh script
        run: |
          chmod +x hello.sh
          ./hello.sh
